set(GTEST_FOUND 1 CACHE INTERNAL "GTEST_FOUND")
set(GTEST_ROOT ${3RD_ROOT}/gtest CACHE INTERNAL "GTEST_ROOT")
set(GTEST_INCLUDE_DIRS ${GTEST_ROOT}/include CACHE INTERNAL "GTEST_INCLUDE_DIRS")
set(GTEST_LIBRARY_DIRS ${GTEST_ROOT}/lib CACHE INTERNAL "GTEST_LIBRARY_DIRS")
file(GLOB LIBRARIES "${GTEST_LIBRARY_DIRS}/*.so")
set(GTEST_LIBRARIES ${LIBRARIES} CACHE INTERNAL "GTEST_LIBRARIES")

include_directories(${GTEST_INCLUDE_DIRS})
link_directories(${GTEST_LIBRARY_DIRS})
